package com.github.winteryoung.yanwte.internals

import com.github.winteryoung.yanwte.YanwteExtensionSpace

/**
 * This is a place holder for those package who doesn't define an extension space.
 */
internal class AutoGeneratedExtensionSpace : YanwteExtensionSpace() {
    override fun initializeImpl() {
        controlFriendAccess = false
    }
}