package com.github.winteryoung.yanwte

import org.junit.Assert
import org.junit.Test

/**
 * @author Winter Young
 * @since 2016/1/26
 */
class YanwteExtensionSpaceTest {
    @Test
    fun testAutoGeneratedContainsThis() {
        AutoGeneratedExtensionSpace().apply {
            initialize("testSpace")
        }.let { space ->
            Assert.assertTrue(space.friends.contains("testSpace"))
        }
    }

    @Test
    fun testAddFriend() {
        object : YanwteExtensionSpace() {
            override fun initializeImpl() {
                addFriendExtSpace("testFriend")
            }
        }.apply {
            initialize("testSpace")
        }.let { space ->
            Assert.assertEquals(2, space.friends.size)
            Assert.assertTrue(space.friends.contains("testFriend"))
        }
    }

    @Test
    fun testIsAuthorizedToWhenNoControl() {
        AutoGeneratedExtensionSpace().apply {
            initialize("testSpace")
        }.let { space ->
            Assert.assertTrue(space.isAuthorizedTo("testXXX"))
        }
    }
    @Test
    fun testIsAuthorizedToWhenControl() {
        object : YanwteExtensionSpace() {
            override fun initializeImpl() {
                addFriendExtSpace("testSpace2")
            }
        }.apply {
            initialize("testSpace")
        }.let { space ->
            Assert.assertTrue(space.isAuthorizedTo("testSpace"))
            Assert.assertTrue(space.isAuthorizedTo("testSpace2"))
            Assert.assertFalse(space.isAuthorizedTo("testXXX"))
        }
    }
}